repos:
  - repo: local
    hooks:
      - id: pre-commit-autoupdate
        name: pre-commit-autoupdate
        entry: pre-commit autoupdate
        language: system
        pass_filenames: false
      - id: hugo-modules-update
        name: hugo-modules-update
        entry: perform update_modules
        language: system
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: mixed-line-ending
