repos:
  - repo: local
    hooks:
      - id: pre-commit-autoupdate
        name: pre-commit-autoupdate
        entry: pre-commit autoupdate
        language: system
        pass_filenames: false
        verbose: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
