baseurl = "http://www.anshulpatel.in/"
title = "Anshul Patel"

theme = "coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-93926186-1"

enableRobotsTXT = true

[params]
    author = "Anshul Patel"
    description = "Geek, Gamer, Techie"
    keywords = "personal,geek,gamer,techie"
    info = "Geek, Gamer, Techie"
    avatarurl = "images/anshul_infostretch.jpg"
    footercontent = "In my spare time, I plan World Domination from a secret villainous lair."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    googleAdSense = "ca-pub-2551124114317762"

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

[taxonomies]
    series = "series"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/anshulpatel25/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 2
    url = "https://gitlab.com/anshulpatel25/"
[[params.social]]
    name = "Reddit"
    icon = "fab fa-reddit"
    weight = 3
    url = "https://www.reddit.com/user/anshulp25/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/anshul-patel-29a95635/"
[[params.social]]
    name = "Steam"
    icon = "fab fa-steam"
    weight = 5
    url = "http://steamcommunity.com/id/anveshak25/"
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope"
    weight = 6
    url = "mailto:anshulpatel25@gmail.com"
[[params.social]]
    name = "Email"
    icon = "fab fa-slideshare"
    weight = 7
    url = "https://www.slideshare.net/anshulpatel5"
[[params.social]]
    name = "Telegram"
    icon = "fab fa-telegram"
    weight = 8
    url = "http://telegram.me/anshulpatel25"
[[params.social]]
    name = "HackerRank"
    icon = "fab fa-hackerrank"
    weight = 9
    url = "https://www.hackerrank.com/anveshak"



[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/post/"

        [[languages.en.menu.main]]
        name = "Meetups"
        weight = 3
        url = "/meetups/"

        [[languages.en.menu.main]]
        name = "Quotes"
        weight = 3
        url = "/files/quotes.html"

    [languages.in-gj]
        languagename = "અમદાવાદી ગુજરાતી"
        title = "અંશુલ પટેલ"

        [languages.in-gj.params]
            author = "અંશુલ પટેલ"
            info = "કંજૂસ, નફટ, ચાંપલો, દોઢ ડાહ્યો"
            description = "મારી મરજી"
            keywords = "personal,geek,gamer,techie"
            footercontent = "જો બકા, વેબસાઈટ તો આપણીજ !"
